=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/DTD/Ej6/agenda.dtd
<!ELEMENT agenda (contacto+)>
<!ELEMENT contacto (nombre, apellidos, numero, foto, email*)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ATTLIST contacto
    id ID #IMPLIED
    relacion (familia|amigo) #IMPLIED
>

<!ATTLIST foto tieneFoto (true|false) "false">

=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/DTD/Ej6/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">

<agenda>

    <contacto id="A" relacion="amigo">

        <nombre>Cipriano</nombre>
        <apellidos>García</apellidos>
        <numero>665777888</numero>
        <foto tieneFoto="true">img.jpg</foto>

    </contacto>

    <contacto id="B" relacion="amigo">

        <nombre>Cristian</nombre>
        <apellidos>Fernández</apellidos>
        <numero>999999777</numero>
        <foto tieneFoto="false">img2.jpg</foto>
        <email>cristian@cr7.com</email>

    </contacto>


</agenda>
