=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/Ej5/pokemon.dtd
<!ELEMENT pokemones (pokemon+)>
<!ELEMENT pokemon (nombre, tipo, nivel, cipri?,ataques+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT ataques (#PCDATA)>
<!ELEMENT cipri EMPTY>

<!ATTLIST pokemon id CDATA #REQUIRED>
<!ATTLIST ataques fuerza CDATA #REQUIRED>

=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/Ej5/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokemones SYSTEM "pokemon.dtd">
<pokemones>

    <pokemon id="1">
        
        <nombre>Pika</nombre>

        <tipo>El√©ctrico</tipo>

        <nivel>67</nivel>

        <ataques fuerza="leve">Cola vital</ataques>    
        <ataques fuerza="mucha">Electropika</ataques>    
        <ataques fuerza="moderada">Pika pika</ataques>

    </pokemon>
     
    <pokemon id="2">
        
        <nombre>Charmander</nombre>

        <tipo>Fuego</tipo>

        <nivel>127</nivel>

         <cipri></cipri>

        <ataques fuerza="mucha">Tormenta de fuego</ataques>    
        <ataques fuerza="moderada">Arder</ataques>    
        <ataques fuerza="leve">Esto va a parecer Murcia en agosto</ataques>
            
    </pokemon>

</pokemones>
