=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/XSD/Ej0/ring.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- definition of simple elements -->
    <xs:element name="Nombre" type="xs:string"/>
    <xs:element name="Raza" type="xs:string"/>
    <xs:element name="Edad" type="xs:positiveInteger"/>

    <!-- definition of complex elements -->
    <xs:element name="Personaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nombre"></xs:element>
                <xs:element ref="Raza"></xs:element>
                <xs:element ref="Edad"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="LordOfTheRings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Personaje" maxOccurs="2" minOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/XSD/Ej0/ring.xml
<?xml version="1.0" encoding="UTF-8"?>

<LordOfTheRings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ring.xsd">

    <Personaje>

        <Nombre>Legolas</Nombre>

        <Raza>Elfo</Raza>

        <Edad>2931</Edad>

    </Personaje>

    <Personaje>

        <Nombre>Gimli</Nombre>

        <Raza>Enano</Raza>

        <Edad>139</Edad>

    </Personaje>

</LordOfTheRings>
