=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/examenxml_alvaro_albarracin/examenxml_alvaro_albarracin/ejercicio 2/universidad.dtd
<!ELEMENT universidad (nombre, rector, facultades, ubicacion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT rector (#PCDATA)>
    <!ELEMENT ubicacion (#PCDATA)>
    <!ELEMENT facultades (facultad+)>
        <!ELEMENT facultad (tipo, director, web?)>
            <!ELEMENT tipo (#PCDATA)>
            <!ELEMENT director (#PCDATA)>
            <!ELEMENT web (#PCDATA)>
        <!ATTLIST facultad acreditada CDATA #REQUIRED>
    <!ATTLIST ubicacion pais NMTOKEN #REQUIRED>
<!ATTLIST universidad tipo NMTOKEN #REQUIRED
                      fundada NMTOKEN #REQUIRED
>

=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/examenxml_alvaro_albarracin/examenxml_alvaro_albarracin/ejercicio 2/universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad SYSTEM "universidad.dtd">

<universidad tipo="Publica" fundada="2020">
    <nombre>UMU</nombre>
    <rector>Cipriano Garcia Hernandez</rector>
    <facultades>
        <facultad acreditada="Si">
            <tipo>Economia</tipo>
            <director>Juan Ferrer</director>
        </facultad>
        <facultad acreditada="No">
            <tipo>Informatica</tipo>
            <director>Cipriano</director>
        </facultad>
        <facultad acreditada="Si">
            <tipo>Medicina</tipo>
            <director>Susana</director>
            <web>www.murciaeduca.es</web>
        </facultad>
    </facultades>
    <ubicacion pais="EspaÃ±a">Murcia</ubicacion>
</universidad>
