=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/examenxml_alvaro_albarracin/examenxml_alvaro_albarracin/ejercicio 3/heladeria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- restrictions of elements -->
    <xs:simpleType name="tipoR">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INDIVIDUAL" />
            <xs:enumeration value="DOBLE" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="precioR">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0.00" />
        </xs:restriction>
    </xs:simpleType>

    <!-- restrictions of attributes -->
    <xs:simpleType name="tlfR">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{9}" />
        </xs:restriction>
    </xs:simpleType>


    <!-- definition of attributes -->
    <xs:attribute name="telefono" type="tlfR" />
    <xs:attribute name="id" type="xs:integer" />
    <xs:attribute name="codigo" type="xs:integer" />
    <xs:attribute name="nombre" type="xs:string" />


    <!-- definition of simple elements -->
    <xs:element name="direccion">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="telefono" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- god will bless u garcher -->
    <xs:element name="vegano">
        <xs:complexType>
            <xs:attribute name="id" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>


    <xs:element name="precio" type="precioR" />
    <xs:element name="tipo" type="tipoR" />


    <!-- definition of complex elements -->
    <xs:element name="helado">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tipo"></xs:element>
                <xs:element ref="precio"></xs:element>
                <xs:element ref="vegano" minOccurs="0"></xs:element>
            </xs:sequence>
            <xs:attribute ref="codigo" use="required"></xs:attribute>
            <xs:attribute ref="nombre" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="postre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="precio"></xs:element>
            </xs:sequence>
            <xs:attribute ref="codigo" use="required"></xs:attribute>
            <xs:attribute ref="nombre" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="heladeria">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="postre"></xs:element>
                <xs:element ref="helado" maxOccurs="3"></xs:element>
                <xs:element ref="direccion"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== AlvaroJoaquinESP/SEGUNDO/LENGUAJE DE MARCAS/UT6-validacion-xml/examenxml_alvaro_albarracin/examenxml_alvaro_albarracin/ejercicio 3/heladeria.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
✓ Atributos cod y nombre son obligatorios.
✓ Tipo solo puede ser INDIVIDUAL y DOBLE.
✓ Precio tiene que ser mayor a 0.00 
✓ Atributo tlf debe tener 9 dígitos.
✓ Vegano es un elemento opcional dentro de helado.
-->

<heladeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="heladeria.xsd">
    <postre codigo="100000" nombre="brownie">
        <precio>5.00</precio>
    </postre>
    <helado codigo="000001" nombre="Vainilla">
        <tipo>INDIVIDUAL</tipo>
        <precio>3.50</precio>
    </helado>
    <helado codigo="000002" nombre="Chocolate">
        <tipo>DOBLE</tipo>
        <precio>5.50</precio>
    </helado>
    <helado codigo="000003" nombre="Pistacho">
        <tipo>DOBLE</tipo>
        <precio>7.00</precio>
        <vegano id="1"/>
    </helado>
    <direccion telefono="612345678">Calle Mayor 1</direccion>
</heladeria>
